/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/earth/scene.gltf -r public/
Author: Omer Bhatti (https://sketchfab.com/OmerBhatti)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/realistic-3d-earth-model-with-4k-textures-4df7ccb1d4344829954ec04be943e885
Title: Realistic 3D Earth Model With 4K Textures
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/earth/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.01, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.atmosphere} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.clouds} />
      </group>
    </group>
  )
}

useGLTF.preload('/earth/scene.gltf')
