/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/earth/scene.gltf -r public/
Author: Omer Bhatti (https://sketchfab.com/OmerBhatti)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/realistic-3d-earth-model-with-4k-textures-4df7ccb1d4344829954ec04be943e885
Title: Realistic 3D Earth Model With 4K Textures
*/

import React, { useRef }  from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, useGLTF } from '@react-three/drei'


const path = '/earth/scene.gltf';
useGLTF.preload(path);

function Earth(props) {

    const earthRef = useRef()
    const atmosRef = useRef()
    const cloudsRef = useRef()

    useFrame(() => {
        earthRef.current.rotation.y += 0.001;
        atmosRef.current.rotation.x += 0.002;
        cloudsRef.current.rotation.x += 0.002
    })
  const { nodes, materials } = useGLTF(path)
  return (
    <group {...props} dispose={null} scale={1.5}>
      <group rotation={[-0.01, 0, -Math.PI / 2]}>
        <mesh ref={earthRef} geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh ref={atmosRef} geometry={nodes.Object_3.geometry} material={materials.atmosphere} />
        <mesh ref={cloudsRef} geometry={nodes.Object_4.geometry} material={materials.clouds} />
      </group>
    </group>
  )
}


export default function Contact() {
  return (
    <section id='contact' className='contact-section'>
        <div className="container my-5">
            <div className="row">
                <div className="col-sm-6" style={{ height: '60vh' }}>
                    <Canvas>
                        <perspectiveCamera />
                        <OrbitControls enableZoom={false}/>
                        <ambientLight color="white" intensity={1.2} />
                        {/* <pointLight color="grey" position={[-4, 1, 3]} intensity={5.2} /> */}
                        <Earth/>
                    </Canvas>
                </div>
                <div className="col-sm-6">
                    <div className="mb-3">
                        <label htmlFor="name" className="form-label">Name</label>
                        <input type="text" className="form-control" id="name" placeholder="Enter your name"/>
                    </div>
                    <div className="mb-3">
                        <label htmlFor="email" className="form-label">Email</label>
                        <input type="email" className="form-control" id="email" placeholder="Enter your email"/>
                    </div>
                    <div className="mb-3">
                        <label htmlFor="subject" className="form-label">Subject</label>
                        <input type="subject" className="form-control" id="subject" placeholder="Enter your subject"/>
                    </div>
                    <div className="mb-3">
                        <label htmlFor="message" className="form-label">Message</label>
                        <textarea className="form-control" id="message" rows="3" placeholder="Write a message"></textarea>
                    </div>
                    <button className="btn btn-primary" type="submit">Send</button>
                </div>
            </div>
        </div>
    </section>
  )
}
